development: &development
  STRIPE_API_KEY: sk_test_Nc1LdRAL1YAqOh60JUTHjI9V
  STRIPE_PUBLIC_KEY: pk_test_VWmJIaOTLzYZAUmg8x7sMKYr

staging:
  STRIPE_API_KEY: sk_test_Nc1LdRAL1YAqOh60JUTHjI9V
  STRIPE_PUBLIC_KEY: pk_test_VWmJIaOTLzYZAUmg8x7sMKYr

production:
  STRIPE_API_KEY: xxx
  STRIPE_PUBLIC_KEY: xxx
